import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className='min-h-full'>
      <div className='px-8 mx-auto max-w-screen-2xl min-h-full'>
      <Navbar />
        {children}
        <Footer />
      </div>
      </div>
      </body>
    </html>
  )
}
